export default {
    LOAD_EVENTS: 'LOAD_EVENTS',
    LOAD_USER: 'LOAD_USER',
    CREATE_USER: 'CREATE_USER',
    LOAD_GROUPS: 'LOAD_GROUPS',
    UPDATE_GROUP: 'UPDATE_GROUP',
    LOAD_LESSONS: 'LOAD_LESSONS'
};
